return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.11.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "left-down",
  width = 512,
  height = 512,
  tilewidth = 32,
  tileheight = 32,
  nextlayerid = 87,
  nextobjectid = 3004,
  backgroundcolor = { 170, 170, 255 },
  properties = {},
  tilesets = {
    {
      name = "imgs",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs2",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "imgs3",
      firstgid = 1,
      class = "",
      tilewidth = 0,
      tileheight = 0,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 0,
      tiles = {}
    },
    {
      name = "_level",
      firstgid = 1,
      class = "",
      tilewidth = 512,
      tileheight = 256,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 2,
      tiles = {
        {
          id = 0,
          image = "gfx/_noise_512_256_20250802_031610.png",
          width = 512,
          height = 256
        },
        {
          id = 1,
          image = "gfx/_noise_512_256_20250821_052916.png",
          width = 512,
          height = 256
        }
      }
    }
  },
  layers = {
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 32,
      name = "bg_deco_texts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {
        {
          id = 2975,
          name = "",
          type = "",
          shape = "text",
          x = 5856,
          y = 10480,
          width = 272,
          height = 96,
          rotation = 0,
          visible = true,
          text = "level 1",
          fontfamily = "Segoe UI",
          pixelsize = 96,
          wrap = true,
          color = { 255, 255, 127 },
          halign = "center",
          valign = "center",
          properties = {}
        },
        {
          id = 2976,
          name = "",
          type = "",
          shape = "text",
          x = 6272,
          y = 10480,
          width = 264,
          height = 96,
          rotation = 0,
          visible = true,
          text = "proto",
          fontfamily = "Segoe UI",
          pixelsize = 96,
          wrap = true,
          color = { 255, 255, 127 },
          halign = "center",
          valign = "center",
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 56,
      name = "bg_deco_shapes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 0, 0 },
      properties = {},
      objects = {
        {
          id = 2792,
          name = "",
          type = "",
          shape = "polygon",
          x = 1544,
          y = 7456,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -64 },
            { x = -24, y = -48 },
            { x = -8, y = -80 },
            { x = -32, y = -72 },
            { x = 0, y = -104 },
            { x = -32, y = -96 },
            { x = 8, y = -128 },
            { x = 32, y = -104 },
            { x = 8, y = -112 },
            { x = 48, y = -80 },
            { x = 16, y = -96 },
            { x = 40, y = -64 },
            { x = 16, y = -80 },
            { x = 40, y = -48 },
            { x = 16, y = -64 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 2877,
          name = "",
          type = "",
          shape = "polygon",
          x = 7504,
          y = 9952,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = -8 },
            { x = 16, y = 0 },
            { x = 24, y = -8 },
            { x = 32, y = 0 },
            { x = 40, y = -8 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 2881,
          name = "",
          type = "",
          shape = "polygon",
          x = 2144,
          y = 7320,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = -8 },
            { x = 16, y = 0 },
            { x = 24, y = -8 },
            { x = 32, y = 0 },
            { x = 40, y = -8 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 2927,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5752,
          y = 10648,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2928,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6112,
          y = 10648,
          width = 120,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2929,
          name = "",
          type = "",
          shape = "polygon",
          x = 7640,
          y = 9952,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = -8 },
            { x = 16, y = 0 },
            { x = 24, y = -8 },
            { x = 32, y = 0 },
            { x = 40, y = -8 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 2932,
          name = "",
          type = "",
          shape = "polygon",
          x = 7784,
          y = 9952,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 8, y = -8 },
            { x = 16, y = 0 },
            { x = 24, y = -8 },
            { x = 32, y = 0 },
            { x = 40, y = -8 },
            { x = 48, y = 0 }
          },
          properties = {}
        },
        {
          id = 2935,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8032,
          y = 9992,
          width = 520,
          height = 696,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2973,
          name = "hint",
          type = "",
          shape = "polyline",
          x = 5768,
          y = 9992,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = -8, y = -8 },
            { x = -8, y = -16 },
            { x = 0, y = -24 },
            { x = 8, y = -32 },
            { x = -8, y = -32 },
            { x = 8, y = -16 },
            { x = 8, y = -32 }
          },
          properties = {}
        },
        {
          id = 2974,
          name = "hint",
          type = "",
          shape = "polyline",
          x = 5696,
          y = 9944,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polyline = {
            { x = 0, y = 0 },
            { x = 8, y = -8 },
            { x = 8, y = -24 },
            { x = 0, y = -32 },
            { x = -8, y = -40 },
            { x = -8, y = -24 },
            { x = 8, y = -40 },
            { x = -8, y = -40 }
          },
          properties = {}
        },
        {
          id = 2979,
          name = "",
          type = "",
          shape = "polygon",
          x = 5520,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -64 },
            { x = -24, y = -48 },
            { x = -8, y = -80 },
            { x = -32, y = -72 },
            { x = 0, y = -104 },
            { x = -32, y = -96 },
            { x = 8, y = -128 },
            { x = 32, y = -104 },
            { x = 8, y = -112 },
            { x = 48, y = -80 },
            { x = 16, y = -96 },
            { x = 40, y = -64 },
            { x = 16, y = -80 },
            { x = 40, y = -48 },
            { x = 16, y = -64 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 2980,
          name = "",
          type = "",
          shape = "polygon",
          x = 5580.8,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -57.6 },
            { x = -21.6, y = -43.2 },
            { x = -7.2, y = -72 },
            { x = -28.8, y = -64.8 },
            { x = 0, y = -93.6 },
            { x = -28.8, y = -86.4 },
            { x = 7.2, y = -115.2 },
            { x = 28.8, y = -93.6 },
            { x = 7.2, y = -100.8 },
            { x = 43.2, y = -72 },
            { x = 14.4, y = -86.4 },
            { x = 36, y = -57.6 },
            { x = 14.4, y = -72 },
            { x = 36, y = -43.2 },
            { x = 14.4, y = -57.6 },
            { x = 14.4, y = 0 }
          },
          properties = {}
        },
        {
          id = 2981,
          name = "",
          type = "",
          shape = "polygon",
          x = 5472,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -64 },
            { x = -24, y = -48 },
            { x = -8, y = -80 },
            { x = -32, y = -72 },
            { x = 0, y = -104 },
            { x = -32, y = -96 },
            { x = 8, y = -128 },
            { x = 32, y = -104 },
            { x = 8, y = -112 },
            { x = 48, y = -80 },
            { x = 16, y = -96 },
            { x = 40, y = -64 },
            { x = 16, y = -80 },
            { x = 40, y = -48 },
            { x = 16, y = -64 },
            { x = 16, y = 0 }
          },
          properties = {}
        },
        {
          id = 2982,
          name = "",
          type = "",
          shape = "polygon",
          x = 5658,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -68 },
            { x = -25.5, y = -51 },
            { x = -8.5, y = -85 },
            { x = -34, y = -76.5 },
            { x = 0, y = -110.5 },
            { x = -34, y = -102 },
            { x = 8.5, y = -136 },
            { x = 34, y = -110.5 },
            { x = 8.5, y = -119 },
            { x = 51, y = -85 },
            { x = 17, y = -102 },
            { x = 42.5, y = -68 },
            { x = 17, y = -85 },
            { x = 42.5, y = -51 },
            { x = 17, y = -68 },
            { x = 17, y = 0 }
          },
          properties = {}
        },
        {
          id = 2983,
          name = "",
          type = "",
          shape = "polygon",
          x = 5697.6,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -51.2 },
            { x = -19.2, y = -38.4 },
            { x = -6.4, y = -64 },
            { x = -25.6, y = -57.6 },
            { x = 0, y = -83.2 },
            { x = -25.6, y = -76.8 },
            { x = 6.4, y = -102.4 },
            { x = 25.6, y = -83.2 },
            { x = 6.4, y = -89.6 },
            { x = 38.4, y = -64 },
            { x = 12.8, y = -76.8 },
            { x = 32, y = -51.2 },
            { x = 12.8, y = -64 },
            { x = 32, y = -38.4 },
            { x = 12.8, y = -51.2 },
            { x = 12.8, y = 0 }
          },
          properties = {}
        },
        {
          id = 2985,
          name = "",
          type = "",
          shape = "polygon",
          x = 6071.94,
          y = 10600,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 0, y = -48 },
            { x = -16.032, y = -36 },
            { x = -5.344, y = -60 },
            { x = -21.376, y = -54 },
            { x = 0, y = -78 },
            { x = -21.376, y = -72 },
            { x = 5.344, y = -96 },
            { x = 21.376, y = -78 },
            { x = 5.344, y = -84 },
            { x = 32.064, y = -60 },
            { x = 10.688, y = -72 },
            { x = 26.72, y = -48 },
            { x = 10.688, y = -60 },
            { x = 26.72, y = -36 },
            { x = 10.688, y = -48 },
            { x = 10.688, y = 0 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 66,
      name = "bg_deco_images04x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 67,
      name = "bg_deco_images04",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 42,
      name = "bg_deco_images03x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 63,
      name = "bg_deco_images03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 64,
      name = "bg_deco_images02x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 41,
      name = "bg_deco_images02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 69,
      name = "bg_deco_imagesx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 29,
      name = "bg_deco_images",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 48,
      name = "*** BG DECO ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 33,
      name = "fg_deco_texts",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 28,
      name = "fg_deco_shapes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 255, 255 },
      properties = {},
      objects = {
        {
          id = 2977,
          name = "",
          type = "",
          shape = "polygon",
          x = 7464,
          y = 10288,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = -16 },
            { x = 32, y = 0 },
            { x = 32, y = -16 },
            { x = 16, y = -32 },
            { x = 0, y = -16 }
          },
          properties = {}
        },
        {
          id = 2978,
          name = "",
          type = "",
          shape = "polygon",
          x = 7464,
          y = 10256,
          width = 0,
          height = 0,
          rotation = 0,
          visible = true,
          polygon = {
            { x = 0, y = 0 },
            { x = 16, y = -16 },
            { x = 32, y = 0 },
            { x = 32, y = -16 },
            { x = 16, y = -32 },
            { x = 0, y = -16 }
          },
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 79,
      name = "fg_deco_images03x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 60,
      name = "fg_deco_images03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 78,
      name = "fg_deco_images02x",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 59,
      name = "fg_deco_images02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 70,
      name = "fg_deco_imagesx",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 30,
      name = "fg_deco_images",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 83,
      name = "*** FG DECO ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 24,
      name = "physics_players",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 170, 0 },
      properties = {},
      objects = {
        {
          id = 654,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5568,
          y = 10520,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 52,
      name = "physics_ground_nmes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2819,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 7040,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2952,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8960,
          y = 9856,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2953,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9040,
          y = 9856,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2954,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9120,
          y = 9856,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2987,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5952,
          y = 10536,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3000,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 9984,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 19,
      name = "physics_ground_nmes02",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2210,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 7088,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2208,
          name = "coins",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 7088,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2955,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 9728,
          y = 10080,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2956,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 9648,
          y = 10080,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2957,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9808,
          y = 10080,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2958,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 9888,
          y = 10080,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2959,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 9968,
          y = 10080,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2993,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 6448,
          y = 10536,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3001,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 5712,
          y = 9984,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 47,
      name = "physics_ground_nmes03",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1291,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 7136,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1287,
          name = "lives",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 7136,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1364,
          name = "kdoorBb",
          type = "",
          shape = "rectangle",
          x = 1632,
          y = 7136,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2960,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10400,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2961,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10496,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2962,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10592,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2963,
          name = "doorBB",
          type = "",
          shape = "rectangle",
          x = 10688,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2964,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10784,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2965,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10880,
          y = 10336,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2988,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5888,
          y = 10536,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2998,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5584,
          y = 9648,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 23,
      name = "physics_flying_nmes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {}
    },
    {
      type = "group",
      id = 49,
      name = "*** PHYSICS_ACTORS ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 84,
      name = "physics_lives",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2461,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1568,
          y = 6912,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2941,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7904,
          y = 9904,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 20,
      name = "physics_coins",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2378,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1504,
          y = 6912,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2849,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5608,
          y = 9648,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2911,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5808,
          y = 9648,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2920,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7504,
          y = 9760,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2921,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7552,
          y = 9792,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2922,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7600,
          y = 9824,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2940,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6088,
          y = 10008,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2942,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8696,
          y = 10000,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2943,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8648,
          y = 10000,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 38,
      name = "physics_keys",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2447,
          name = "mvgrAA",
          type = "",
          shape = "rectangle",
          x = 1632,
          y = 6912,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2890,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 1696,
          y = 6912,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2910,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 5496,
          y = 9512,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 50,
      name = "*** PHYSICS_COLLECTIBLES ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 7,
      name = "physics_grounds",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 67, 0, 0 },
      properties = {},
      objects = {
        {
          id = 2984,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 7072,
          width = 256,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 1837,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 10600,
          width = 672,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2205,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7496,
          y = 9952,
          width = 544,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2371,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 9280,
          width = 344,
          height = 1328,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2524,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5424,
          y = 9280,
          width = 1352,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2546,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6576,
          y = 10304,
          width = 1464,
          height = 384,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2583,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 9696,
          width = 96,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2586,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5424,
          y = 10064,
          width = 952,
          height = 280,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2806,
          name = "",
          type = "",
          shape = "rectangle",
          x = 9464,
          y = 10144,
          width = 744,
          height = 544,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2807,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5856,
          y = 9400,
          width = 160,
          height = 360,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2814,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8768,
          y = 9920,
          width = 704,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2838,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6768,
          y = 9280,
          width = 440,
          height = 816,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2841,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8672,
          y = 9280,
          width = 2968,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2844,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8544,
          y = 9984,
          width = 64,
          height = 704,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2846,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6864,
          y = 10088,
          width = 240,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2892,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8256,
          y = 9952,
          width = 96,
          height = 736,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2902,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6368,
          y = 10240,
          width = 128,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2904,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 10056,
          width = 192,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2908,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5536,
          y = 9696,
          width = 144,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2923,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5864,
          y = 10600,
          width = 256,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2924,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6224,
          y = 10600,
          width = 360,
          height = 88,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2945,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8600,
          y = 10048,
          width = 176,
          height = 640,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2948,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8672,
          y = 9480,
          width = 48,
          height = 488,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2950,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10200,
          y = 10400,
          width = 872,
          height = 288,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2951,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11064,
          y = 10528,
          width = 600,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2966,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10656,
          y = 9480,
          width = 760,
          height = 768,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 12,
      name = "physics_ladders",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 44, 0, 0 },
      properties = {},
      objects = {
        {
          id = 2821,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 7168,
          width = 32,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2882,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6544,
          y = 10304,
          width = 32,
          height = 296,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "physics_ptpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 170, 0, 127 },
      properties = {},
      objects = {
        {
          id = 2547,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 7040,
          width = 192,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2901,
          name = "t",
          type = "",
          shape = "rectangle",
          x = 6544,
          y = 10304,
          width = 32,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2903,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6376,
          y = 10152,
          width = 104,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2912,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5464,
          y = 9560,
          width = 104,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2947,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8720,
          y = 9968,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "physics_steps",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 255, 0 },
      properties = {},
      objects = {
        {
          id = 2579,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 7168,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2905,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6176,
          y = 10060,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2906,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6016,
          y = 10060,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2913,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6344,
          y = 10072,
          width = 32,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2937,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8256,
          y = 9956,
          width = 96,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 22,
      name = "physics_walls",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 85, 127 },
      properties = {},
      objects = {
        {
          id = 2817,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 7168,
          width = 32,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2842,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5664,
          y = 9704,
          width = 16,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2907,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5792,
          y = 9704,
          width = 16,
          height = 272,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2909,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5416,
          y = 9504,
          width = 16,
          height = 512,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 86,
      name = "physics_mvpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 85, 127 },
      properties = {},
      objects = {
        {
          id = 2810,
          name = "idAAdx64dy32vel6dirL",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 7328,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2933,
          name = "idAAdx168dy0vel6dirR",
          type = "",
          shape = "rectangle",
          x = 8040,
          y = 9960,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "physics_ptmvpfs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 85, 255 },
      properties = {},
      objects = {
        {
          id = 2449,
          name = "idAAdx64dy32vel6dirL",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 7296,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2938,
          name = "idAAdx256dy0vel6dirR",
          type = "",
          shape = "rectangle",
          x = 8352,
          y = 9960,
          width = 64,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 82,
      name = "physics_doors",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 45, 90, 135 },
      properties = {},
      objects = {
        {
          id = 2856,
          name = "doorAAdx0dy128vel16dirU",
          type = "",
          shape = "rectangle",
          x = 1920,
          y = 6912,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2857,
          name = "doorAAdx0dy104vel16dirU",
          type = "",
          shape = "rectangle",
          x = 5592,
          y = 9960,
          width = 32,
          height = 104,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2865,
          name = "doorZZdx96dy0vel16dirL",
          type = "",
          shape = "rectangle",
          x = 2016,
          y = 6912,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2914,
          name = "doorAAdx0dy136vel16dirU",
          type = "",
          shape = "rectangle",
          x = 6960,
          y = 10168,
          width = 32,
          height = 136,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2967,
          name = "doorBBdx0dy160vel24dirU",
          type = "",
          shape = "rectangle",
          x = 11000,
          y = 10240,
          width = 32,
          height = 160,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 44,
      name = "physics_sensors",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 85, 170, 255 },
      properties = {},
      objects = {
        {
          id = 2860,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 1952,
          y = 6912,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2851,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 5504,
          y = 9952,
          width = 32,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2852,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5472,
          y = 9856,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2861,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 5680,
          y = 9952,
          width = 32,
          height = 112,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2862,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5712,
          y = 9856,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2864,
          name = "doorZZ",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 6912,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2868,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2080,
          y = 6912,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2869,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1984,
          y = 6912,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2915,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 6832,
          y = 10096,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2916,
          name = "",
          type = "",
          shape = "rectangle",
          x = 6800,
          y = 10096,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2917,
          name = "doorAA",
          type = "",
          shape = "rectangle",
          x = 7104,
          y = 10096,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2918,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7136,
          y = 10096,
          width = 32,
          height = 208,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2968,
          name = "doorBB",
          type = "",
          shape = "rectangle",
          x = 10880,
          y = 10248,
          width = 32,
          height = 152,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2969,
          name = "",
          type = "",
          shape = "rectangle",
          x = 10840,
          y = 10248,
          width = 32,
          height = 152,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "physics_springs",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 127 },
      properties = {},
      objects = {
        {
          id = 2875,
          name = "vx0vy20",
          type = "",
          shape = "rectangle",
          x = 2112,
          y = 7168,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2919,
          name = "vx0vy20",
          type = "",
          shape = "rectangle",
          x = 7464,
          y = 10304,
          width = 32,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 40,
      name = "physics_spikes",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 255, 0, 0 },
      properties = {},
      objects = {
        {
          id = 2879,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7504,
          y = 9952,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2880,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2144,
          y = 7320,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2930,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7640,
          y = 9952,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2931,
          name = "",
          type = "",
          shape = "rectangle",
          x = 7784,
          y = 9952,
          width = 48,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 27,
      name = "physics_voids",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 0, 255 },
      properties = {},
      objects = {
        {
          id = 2887,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2048,
          y = 7232,
          width = 96,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2884,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5696,
          y = 10688,
          width = 608,
          height = 40,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2934,
          name = "",
          type = "",
          shape = "rectangle",
          x = 8040,
          y = 10240,
          width = 504,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 31,
      name = "physics_exits",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      tintcolor = { 0, 170, 255 },
      properties = {},
      objects = {
        {
          id = 2854,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11640,
          y = 10216,
          width = 24,
          height = 312,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2855,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2152,
          y = 6912,
          width = 24,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 51,
      name = "*** PHYSICS_WORLD ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {}
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 45,
      name = "physics_map_def",
      class = "",
      visible = true,
      opacity = 0.4,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 5088,
          y = 9280,
          width = 6552,
          height = 1408,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 76,
      name = "level",
      class = "",
      visible = true,
      opacity = 0.25,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 2900,
          name = "",
          type = "",
          shape = "rectangle",
          x = 2768,
          y = 6800,
          width = 11648,
          height = 5824,
          rotation = 0,
          gid = 1,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "group",
      id = 53,
      name = "*** REFS ***",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      layers = {
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 77,
          name = "annotations",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 2516,
              name = "",
              type = "",
              shape = "text",
              x = 960,
              y = 7136,
              width = 264,
              height = 96,
              rotation = 0,
              visible = true,
              text = "forest",
              fontfamily = "Segoe UI",
              pixelsize = 96,
              wrap = true,
              color = { 255, 255, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2521,
              name = "",
              type = "",
              shape = "text",
              x = 960,
              y = 7248,
              width = 440,
              height = 112,
              rotation = 0,
              visible = true,
              text = "GIDEROS",
              fontfamily = "Segoe UI",
              pixelsize = 96,
              wrap = true,
              color = { 255, 255, 127 },
              bold = true,
              underline = true,
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2894,
              name = "",
              type = "",
              shape = "text",
              x = 1504,
              y = 6872,
              width = 136,
              height = 32,
              rotation = 0,
              visible = true,
              text = "collectibles",
              fontfamily = "Segoe UI",
              pixelsize = 27,
              wrap = true,
              color = { 170, 0, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2895,
              name = "",
              type = "",
              shape = "text",
              x = 1504,
              y = 7000,
              width = 72,
              height = 32,
              rotation = 0,
              visible = true,
              text = "nmes",
              fontfamily = "Segoe UI",
              pixelsize = 27,
              wrap = true,
              color = { 170, 0, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2896,
              name = "",
              type = "",
              shape = "text",
              x = 960,
              y = 6872,
              width = 136,
              height = 32,
              rotation = 0,
              visible = true,
              text = "references",
              fontfamily = "Segoe UI",
              pixelsize = 27,
              wrap = true,
              color = { 170, 0, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2897,
              name = "",
              type = "",
              shape = "text",
              x = 1920,
              y = 6872,
              width = 96,
              height = 32,
              rotation = 0,
              visible = true,
              text = "physics",
              fontfamily = "Segoe UI",
              pixelsize = 27,
              wrap = true,
              color = { 170, 0, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            },
            {
              id = 2898,
              name = "",
              type = "",
              shape = "text",
              x = 1504,
              y = 7288,
              width = 96,
              height = 32,
              rotation = 0,
              visible = true,
              text = "shapes",
              fontfamily = "Segoe UI",
              pixelsize = 27,
              wrap = true,
              color = { 170, 0, 127 },
              halign = "center",
              valign = "center",
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 26,
          name = "physics_mvpfs_REFS",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          tintcolor = { 255, 255, 255 },
          properties = {},
          objects = {
            {
              id = 2450,
              name = "",
              type = "",
              shape = "rectangle",
              x = 960,
              y = 7072,
              width = 288,
              height = 8,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        },
        {
          type = "objectgroup",
          draworder = "topdown",
          id = 36,
          name = "level_design_REFS",
          class = "",
          visible = true,
          opacity = 1,
          offsetx = 0,
          offsety = 0,
          parallaxx = 1,
          parallaxy = 1,
          properties = {},
          objects = {
            {
              id = 1348,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1088,
              y = 6912,
              width = 160,
              height = 128,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2558,
              name = "",
              type = "",
              shape = "rectangle",
              x = 1024,
              y = 6912,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2564,
              name = "",
              type = "",
              shape = "rectangle",
              x = 960,
              y = 6912,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2828,
              name = "",
              type = "",
              shape = "rectangle",
              x = 5528,
              y = 9592,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2834,
              name = "",
              type = "",
              shape = "rectangle",
              x = 6400,
              y = 10048,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2926,
              name = "",
              type = "",
              shape = "rectangle",
              x = 5760,
              y = 10648,
              width = 112,
              height = 24,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2936,
              name = "",
              type = "",
              shape = "rectangle",
              x = 8040,
              y = 9968,
              width = 168,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2939,
              name = "",
              type = "",
              shape = "rectangle",
              x = 8352,
              y = 9968,
              width = 256,
              height = 16,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2944,
              name = "",
              type = "",
              shape = "rectangle",
              x = 8744,
              y = 9944,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            },
            {
              id = 2949,
              name = "",
              type = "",
              shape = "rectangle",
              x = 11072,
              y = 10400,
              width = 24,
              height = 104,
              rotation = 0,
              visible = true,
              properties = {}
            }
          }
        }
      }
    }
  }
}
